pipeline:
  identifier: Build_harness_1693448032798
  name: Build harness
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: opa-checks
        identifier: opachecks
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: hello-world
                  identifier: helloworld
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "hello world"
                          echo "$(ls -la)"
                          echo "$(whoami)"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
