pipeline:
  identifier: Build_harness_1693448032798
  name: Build harness
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: opa-checks
        identifier: opachecks
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - parallel:
                  - step:
                      type: ShellScript
                      name: hello-world
                      identifier: helloworld
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: |-
                              echo "hello world"
                              echo "$(ls -la)"
                              echo "$(whoami)"
                              echo "$(pwd)"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
                  - step:
                      type: ShellScript
                      name: create-file
                      identifier: createfile
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: echo "test" > test.txt
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
              - step:
                  type: Container
                  name: gator
                  identifier: gator
                  spec:
                    connectorRef: dockerhubmain
                    image: alpine
                    command: |-
                      echo "running opa checks"
                      echo "$(pwd)"
                      echo $(whoami)
                    shell: Sh
                    infrastructure:
                      type: KubernetesDirect
                      spec:
                        connectorRef: gkecluster1
                        namespace: default
                        resources:
                          limits:
                            cpu: "0.5"
                            memory: 500Mi
                        annotations: {}
                        labels: {}
                        containerSecurityContext:
                          capabilities:
                            drop: []
                            add: []
                          runAsNonRoot: true
                        nodeSelector: {}
                        automountServiceAccountToken: true
                    outputVariables: []
                    envVariables: {}
                    imagePullPolicy: IfNotPresent
                  timeout: 1m
        tags: {}
