pipeline:
  identifier: Build_harness_1693448032798
  name: Build harness
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: opa-checks
        identifier: opachecks
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: sleep
                  identifier: sleep
                  spec:
                    duration: 10m
        tags: {}
