pipeline:
  identifier: Build_harness_1693448032798
  name: Build harness
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: opa-checks
        identifier: opachecks
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - parallel:
                  - step:
                      type: ShellScript
                      name: hello-world
                      identifier: helloworld
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: |-
                              echo "hello world"
                              echo "$(ls -la)"
                              echo "$(whoami)"
                              echo "$(pwd)"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
                  - step:
                      type: ShellScript
                      name: create-file
                      identifier: createfile
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: echo "test" > test.txt
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
              - step:
                  type: Container
                  name: gator
                  identifier: gator
                  spec:
                    connectorRef: dockerhubmain
                    image: alpine
                    command: |-
                      echo "running opa checks"
                      echo "$(pwd)"
                      echo $(whoami)
                      echo "Env var H_TEST --> ${H_TEST}"
                    shell: Sh
                    infrastructure:
                      type: KubernetesDirect
                      spec:
                        connectorRef: gkecluster1
                        namespace: harness-delegate-ng
                        resources:
                          limits:
                            cpu: "0.5"
                            memory: 500Mi
                        annotations: {}
                        labels:
                          app_id: "0000"
                        containerSecurityContext:
                          capabilities:
                            drop: []
                            add: []
                          runAsNonRoot: false
                        nodeSelector: {}
                        automountServiceAccountToken: true
                    outputVariables: []
                    envVariables:
                      H_TEST: ENV_VAR
                    imagePullPolicy: IfNotPresent
                  timeout: 1m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
        tags: {}
  notificationRules:
    - name: email-notify
      identifier: emailnotify
      pipelineEvents:
        - type: AllEvents
        - type: PipelineStart
        - type: PipelineEnd
        - type: PipelineSuccess
        - type: PipelineFailed
        - type: StageFailed
        - type: StageSuccess
        - type: StageStart
        - type: StepFailed
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - erodg2013@gmail.com
      enabled: true
